import {
  Angry,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  AtSign,
  BadgeCheck,
  BadgeInfo,
  Bell,
  Bot,
  Braces,
  BrainCircuit,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleUserRound,
  CircleX,
  Clapperboard,
  Clock3,
  CloudUpload,
  Code2,
  Coffee,
  Compass,
  Copy,
  ExternalLink,
  Eye,
  FileCode2,
  Flame,
  Frown,
  Gauge,
  GraduationCap,
  Heart,
  History,
  House,
  Image,
  ImageUp,
  Inbox,
  Info,
  Languages,
  Laugh,
  Layers3,
  Link,
  List,
  ListOrdered,
  LoaderCircle,
  LogOut,
  Megaphone,
  Meh,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquareMore,
  MessageSquareText,
  MessagesSquare,
  Moon,
  Newspaper,
  Palette,
  PenTool,
  Plus,
  QrCode,
  RefreshCw,
  Save,
  Search,
  SearchX,
  Send,
  Settings2,
  Share2,
  ShieldCheck,
  SlidersHorizontal,
  Smile,
  Sparkles,
  SquarePen,
  Star,
  Sun,
  ThumbsUp,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  UserRound,
  Users,
  WandSparkles,
  Waves,
  X,
} from 'lucide-vue-next'
import type { Component } from 'vue'

/**
 * Explicit registry so only the icons the prototype actually uses end up in the
 * bundle, while data-driven `icon` fields can still be resolved by name.
 */
export const iconRegistry: Record<string, Component> = {
  'angry': Angry,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-right': ArrowUpRight,
  'at-sign': AtSign,
  'badge-check': BadgeCheck,
  'badge-info': BadgeInfo,
  'bell': Bell,
  'bot': Bot,
  'braces': Braces,
  'brain-circuit': BrainCircuit,
  'chart-no-axes-combined': ChartNoAxesCombined,
  'check': Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-help': CircleHelp,
  'circle-user-round': CircleUserRound,
  'circle-x': CircleX,
  'clapperboard': Clapperboard,
  'clock-3': Clock3,
  'cloud-upload': CloudUpload,
  'code-2': Code2,
  'coffee': Coffee,
  'compass': Compass,
  'copy': Copy,
  'external-link': ExternalLink,
  'eye': Eye,
  'file-code-2': FileCode2,
  'flame': Flame,
  'frown': Frown,
  'gauge': Gauge,
  'graduation-cap': GraduationCap,
  'heart': Heart,
  'history': History,
  'house': House,
  'image': Image,
  'image-up': ImageUp,
  'inbox': Inbox,
  'info': Info,
  'languages': Languages,
  'laugh': Laugh,
  'layers-3': Layers3,
  'link': Link,
  'list': List,
  'list-ordered': ListOrdered,
  'loader-circle': LoaderCircle,
  'log-out': LogOut,
  'megaphone': Megaphone,
  'meh': Meh,
  'menu': Menu,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'message-square-more': MessageSquareMore,
  'message-square-text': MessageSquareText,
  'messages-square': MessagesSquare,
  'moon': Moon,
  'newspaper': Newspaper,
  'palette': Palette,
  'pen-tool': PenTool,
  'plus': Plus,
  'qr-code': QrCode,
  'refresh-cw': RefreshCw,
  'save': Save,
  'search': Search,
  'search-x': SearchX,
  'send': Send,
  'settings-2': Settings2,
  'share-2': Share2,
  'shield-check': ShieldCheck,
  'sliders-horizontal': SlidersHorizontal,
  'smile': Smile,
  'sparkles': Sparkles,
  'square-pen': SquarePen,
  'star': Star,
  'sun': Sun,
  'thumbs-up': ThumbsUp,
  'trash-2': Trash2,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'trophy': Trophy,
  'user-round': UserRound,
  'users': Users,
  'wand-sparkles': WandSparkles,
  'waves': Waves,
  'x': X,
}

export function resolveIcon(name: string): Component {
  return iconRegistry[name] ?? Sparkles
}
